version: "3.8"
services:
 keycloak:
   container_name: keycloak
   image: jboss/keycloak
   ports:
     - '8080:8080'
   environment:
     DB_VENDOR: MYSQL
     DB_ADDR: mysql_db
     DB_PORT: 3306
     DB_DATABASE: core_bank
     DB_USER: hieudx1
     DB_PASSWORD: 123456789
     DB_JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
     KEYCLOAK_USER: admin
     KEYCLOAK_PASSWORD: 123456789
     KC_HEALTH_ENABLED: true
     KC_METRICS_ENABLED: true
     KC_LOG_LEVEL: info
     KC_HTTP_PORT: 8080
     KC_HOSTNAME: keycloak
     KC_HOSTNAME-ADMIN-URL: http://localhost:8080/auth/realms/hieudx-internet-banking
   restart: always
#    volumes:
#      - .keycloak/:/opt/keycloak/data/h2/
   depends_on:
     mysql_db:
       condition: service_healthy
   networks:
     - dube_internal
   healthcheck:
     test: ["CMD", "curl", "--head","fsS", "http://localhost:8080/health/ready"]
     interval: 15s
     timeout: 2s
     retries: 15
 mysql_db:
   container_name: mysql_db
   restart: always
   image: mysql:8.0
   volumes:
     - db:/var/lib/mysql
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
     - "MYSQL_DATABASE=core_bank"
     - "MYSQL_USER=hieudx1"
     - "MYSQL_PASSWORD=123456789"
     - "MYSQL_ROOT_PASSWORD=123456789"
   ports:
     - "3309:3306"
   networks:
     - dube_internal
   healthcheck:
     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
     timeout: 20s
     retries: 10
    
networks:
  dube_internal:
    driver: bridge


volumes:
  db:
    driver: local
